#!/usr/bin/env perl

package ipamsh;
use warnings;
use strict;
use Data::Dumper;
use lib 'lib';
use phpipam::API;

# process config file
my %config = parse_config("api.conf");

my $url  = $config{'url'};
my $prot = $config{'protocol'};
my $api  = $config{'api'};
my $user = $config{'user'};
my $pass = $config{'password'};

my %actions = (
    vlans => {
        ls  => \&getvlans,
        add => \&addvlan,
        cat => \&catvlan,
        rm  => \&delvlan,
    },
    subnets => {
        ls  => \&getsubnets,
        add => \&addsubnet,
        cat => \&catsubnet,
        rm  => \&delvlan,
        req => "section id",
    },
    devices => {
        ls  => \&getdevices,
        add => \&adddevice,
        cat => \&catdevice,
        rm  => \&deldevice,
    },
    sections => {
        ls  => \&getsections,
        add => \&addsection,
        cat => \&catsection,
        rm  => \&delsection,
    },
);

sub parse_config {
    my $file = shift;
    my %answer;

    open CONFIG, "$file" or die "Couldn't read config file $file: $!\n";
    while (<CONFIG>) {

        # skip blanks and comments
        next if (/^#|^\s*$/);
        my ( $variable, $value ) = split /=/;

        # remove char returns
        chomp $variable;
        chomp $value;

        # assing to hash
        $answer{$variable} = $value;
    }
    close CONFIG;

    return %answer;
}

my $ipam = phpipam::API->new(
    proto    => $prot,
    url      => $url,
    api      => $api,
    user     => $user,
    password => $pass,
);

my $token = undef;

use base qw(Term::Shell);

my @controllers =
  qw/ sections subnets folders vlans addresses l2domains vrfs devices tools/;

sub prompt_str {
    my $self = shift;
    return $self->{'prompt'};
}

sub base {
    my ($self) = @_;
    unless ( $self->{'base'} ) {
        $self->{'base'} = "root";
    }
}

sub update_prompt {
    my ($self) = @_;
    my $base = $self->base();
    $self->{'prompt'} = "$base > ";
    return;
}

sub help_ls {
    << "END";
ls 
    In the root of the api, outputs available ipam controllers.
    In controller context, outputs a listing of objects of the respective controller
END
}

sub run_ls {
    my ($self, @args) = @_;
    my $base = $self->{base};
    if ( $self->{base} eq "root" ) {
        for my $controller (@controllers) {
            print "$controller\n";
        }
    }
    elsif ( exists $actions{$base}{req} ) {
        if ( defined $args[0]  and $args[0] eq "-i" ) {
        $actions{$base}{ls}->($args[0]) ;

        }
        print "we need a " . $actions{$base}{req} . " to ls this controller\n";
        print "run ls -i <id> \n";
        print "you should probably need to run cd section, cat <section> to get";
        print "the section id you require\n";
    }
    else {
        $actions{$base}{ls}->();

    }
}

sub run_pwd {
    my ($self) = @_;
    print $self->base(), "\n";
    $self->update_prompt( $self->base );
    return;
}

sub help_cd {
    << "END";
cd <controller>:
    enter the <controller> context. You may use tab completion to find available controllers.
    Without arguments, cd goes back to the root context.
END
}

sub run_cd {
    my ( $self, $controller ) = @_;
    if ( !$controller ) {
        $controller = "root";
    }

    # update base
    $self->{'base'} = $controller;

    # update prompt
    $self->update_prompt;
    return;
}

sub comp_cd {
    my ( $self, $controller ) = @_;
    $self->completions( $controller, \@controllers );
}

sub run_show_token {
    my $self = shift;
    print "Authentication token: " . $token, "\n";
}

sub run_logoff {
    my $self = shift;

    eval { $ipam->delete_token($token); };
    if ($@) {
        print $@;
    }
    print "okay bye\n";
    exit 0;
}

sub getsections {
    my $sections = eval { $ipam->get_sections($token); };
    if ($@) {
        print "Something went wrong getting the sections info: " . $@;
    }
    if ( scalar(@$sections) > 0 ) {
        print "Found " . scalar @$sections . " section[s]:\n";

        printf( "%20s %s\n", "name", "id" );
        for my $section (@$sections) {
            printf( "%20s %d\n", $section->{name}, $section->{id} ); 
        }
    }
    else {
        print "sorry, no sections found yet\n";
    }

}

sub getvlans {
    my $vlans = eval { $ipam->get_vlans($token); };
    if ($@) {
        print "Something went wrong getting the vlans info: " . $@;
    }
    if ( scalar(@$vlans) > 0 ) {
        print "Found " . scalar @$vlans . " vlan[s]:\n";

        for my $vlan (@$vlans) {
            print "\t" . $vlan->{name}, "\n";
        }
    }
    else {
        print "sorry, no vlans found yet\n";
    }

}

sub getsubnets {
    my ( $self, %args ) = shift;
    my $subnets = eval { $ipam->get_subnets( toke => $token, id => $args{id},); };
    if ($@) {
        print "Something went wrong getting the subnets info: " . $@;
    }
    if ( scalar(@$subnets) > 0 ) {
        print "Found " . scalar @$subnets . " subnet[s]:\n";

        for my $subnet (@$subnets) {
            print "\t" . $subnet->{name}, "\n";
        }
    }
    else {
        print "sorry, no subnets found yet\n";
    }

}

sub getdevices {
    my $devices = eval { $ipam->get_devices($token); };
    if ($@) {
        print "Something went wrong getting the devices info: " . $@;
    }
    if ( scalar(@$devices) > 0 ) {
        print "Found " . scalar @$devices . " device[s]:\n";

        for my $device (@$devices) {
            print "\t" . $device->{name}, "\n";
        }
    }
    else {
        print "sorry, no devices found yet\n";
    }

}

sub init {
    my $self = shift;

    # update the prompt here or it will not work!!
    $self->update_prompt();

    # login ipam
    $token = eval { $ipam->get_token; };
    if ($@) {
        print "something went wrong\n";
        print "$@\n";
    }
}

sub fini {

    #    run_logoff();
    print "\n";
}

package main;
my $shell = ipamsh->new;
$shell->cmdloop;

